[package]
name = "mogo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termsize = "0.1.6"
[target.'cfg(windows)'.dependencies]
winapi-util = "0.1"
